name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Trigger this workflow whenever there's a push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use an Ubuntu runner for the build process

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to check out your repository code

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Action to set up Node.js environment
        with:
          node-version: '20' # Specify the Node.js version you want to use (e.g., '18', '20', or '22' LTS)
          cache: 'npm' # Cache npm dependencies for faster builds

      - name: Install dependencies
        run: npm install # Install all project dependencies

      - name: Build React app
        run: npm run build # Run your React app's build script

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # A popular action for deploying to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
          publish_dir: ./build # The directory containing your built static files
          publish_branch: gh-pages # The branch to deploy to (GitHub Pages serves from this branch)
          # cname: example.com # Uncomment and set if you use a custom domain
