name: Process Invoice CSV and Send Report

on:
  push:
    branches:
      - main # Or your default branch if different
    paths:
      - 'input.csv' # Only trigger if input.csv is pushed/updated

jobs:
  build-and-send-report:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Allows checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Specify a recent Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run script to build report
        run: python build_report.py

      - name: Send email with report attachment
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server credentials:
          server_address: smtp.gmail.com # Example for Gmail, change if using another provider
          server_port: 465 # Standard SSL port, change if needed (e.g., 587 for TLS)
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          # Required email content:
          subject: "Automated Invoice Report - {{ env.GITHUB_REPOSITORY }} - {{ env.GITHUB_RUN_NUMBER }}"
          body: |
            Please find attached the latest invoice report.
            This report was automatically generated by a GitHub Action.
            Workflow Run ID: ${{ github.run_id }}
            Commit SHA: ${{ github.sha }}
          to: ${{ secrets.MAIL_RECIPIENTS }} # Comma-separated list
          from: GitHub Actions <${{ secrets.MAIL_USERNAME }}> # Optional: customize sender name

          # Attachment:
          attachments: report.html

          # Optional settings:
          # secure: true # Use true for SSL (port 465), false or remove for TLS (port 587) - true is default with port 465
          # html_body: true # Set to true if your body content is HTML
          # priority: high
          # cc: ${{ secrets.MAIL_CC_RECIPIENTS }} # Optional CC recipients
          # bcc: ${{ secrets.MAIL_BCC_RECIPIENTS }} # Optional BCC recipients
          # reply_to: your-reply-to@example.com # Optional reply-to address
          # convert_markdown: true # If your body is markdown and you want it converted to HTML
          # ignore_cert: false # Set to true if your mail server uses a self-signed certificate (not recommended)
          # tls_server_name: # Specify TLS server name if different from server_address

    outputs:
      report_file_name: report.html # To potentially use in other jobs if needed
      run_id: ${{ github.run_id }}
